package com.agree.framework.web.form.administration;

import java.util.Date;

/**
 * TBsmsEventtaskId generated by MyEclipse Persistence Tools
 */

public class TBsmsEventtask implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String channelcode;
	private String channeldate;
	private String channelserno;
	private String tasksql;
	private String listenevent;
	private String resultobject;
	private Date starttime;
	private Date endtime;
	
	private String centerstatus;
	private String enabled;
	private String usercode;
	private String tempath;

	// Constructors

	public String getTempath() {
		return tempath;
	}

	public void setTempath(String tempath) {
		this.tempath = tempath;
	}

	public String getCenterstatus() {
		return centerstatus;
	}

	public void setCenterstatus(String centerstatus) {
		this.centerstatus = centerstatus;
	}

	public String getEnabled() {
		return enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	/** default constructor */
	public TBsmsEventtask() {
	}

	/** minimal constructor */
	public TBsmsEventtask(String channelcode, String channeldate,
			String channelserno, String listenevent) {
		this.channelcode = channelcode;
		this.channeldate = channeldate;
		this.channelserno = channelserno;
		this.listenevent = listenevent;
	}

	/** full constructor */
	public TBsmsEventtask(String channelcode, String channeldate,
			String channelserno, String tasksql, String listenevent,
			String resultobject, Date starttime, Date endtime, String tempath) {
		this.channelcode = channelcode;
		this.channeldate = channeldate;
		this.channelserno = channelserno;
		this.tasksql = tasksql;
		this.listenevent = listenevent;
		this.resultobject = resultobject;
		this.starttime = starttime;
		this.endtime = endtime;
		this.tempath= tempath;
	}

	// Property accessors

	public String getChannelcode() {
		return this.channelcode;
	}

	public void setChannelcode(String channelcode) {
		this.channelcode = channelcode;
	}

	public String getChanneldate() {
		return this.channeldate;
	}

	public void setChanneldate(String channeldate) {
		this.channeldate = channeldate;
	}

	public String getChannelserno() {
		return this.channelserno;
	}

	public void setChannelserno(String channelserno) {
		this.channelserno = channelserno;
	}

	public String getTasksql() {
		return this.tasksql;
	}

	public void setTasksql(String tasksql) {
		this.tasksql = tasksql;
	}

	public String getListenevent() {
		return this.listenevent;
	}

	public void setListenevent(String listenevent) {
		this.listenevent = listenevent;
	}

	public String getResultobject() {
		return this.resultobject;
	}

	public void setResultobject(String resultobject) {
		this.resultobject = resultobject;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TBsmsEventtask))
			return false;
		TBsmsEventtask castOther = (TBsmsEventtask) other;

		return ((this.getChannelcode() == castOther.getChannelcode()) || (this
				.getChannelcode() != null
				&& castOther.getChannelcode() != null && this.getChannelcode()
				.equals(castOther.getChannelcode())))
				&& ((this.getChanneldate() == castOther.getChanneldate()) || (this
						.getChanneldate() != null
						&& castOther.getChanneldate() != null && this
						.getChanneldate().equals(castOther.getChanneldate())))
				&& ((this.getChannelserno() == castOther.getChannelserno()) || (this
						.getChannelserno() != null
						&& castOther.getChannelserno() != null && this
						.getChannelserno().equals(castOther.getChannelserno())))
				&& ((this.getTasksql() == castOther.getTasksql()) || (this
						.getTasksql() != null
						&& castOther.getTasksql() != null && this.getTasksql()
						.equals(castOther.getTasksql())))
				&& ((this.getListenevent() == castOther.getListenevent()) || (this
						.getListenevent() != null
						&& castOther.getListenevent() != null && this
						.getListenevent().equals(castOther.getListenevent())))
				&& ((this.getResultobject() == castOther.getResultobject()) || (this
						.getResultobject() != null
						&& castOther.getResultobject() != null && this
						.getResultobject().equals(castOther.getResultobject())))
				&& ((this.getStarttime() == castOther.getStarttime()) || (this
						.getStarttime() != null
						&& castOther.getStarttime() != null && this
						.getStarttime().equals(castOther.getStarttime())))
				&& ((this.getEndtime() == castOther.getEndtime()) || (this
						.getEndtime() != null
						&& castOther.getEndtime() != null && this.getEndtime()
						.equals(castOther.getEndtime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getChannelcode() == null ? 0 : this.getChannelcode()
						.hashCode());
		result = 37
				* result
				+ (getChanneldate() == null ? 0 : this.getChanneldate()
						.hashCode());
		result = 37
				* result
				+ (getChannelserno() == null ? 0 : this.getChannelserno()
						.hashCode());
		result = 37 * result
				+ (getTasksql() == null ? 0 : this.getTasksql().hashCode());
		result = 37
				* result
				+ (getListenevent() == null ? 0 : this.getListenevent()
						.hashCode());
		result = 37
				* result
				+ (getResultobject() == null ? 0 : this.getResultobject()
						.hashCode());
		result = 37 * result
				+ (getStarttime() == null ? 0 : this.getStarttime().hashCode());
		result = 37 * result
				+ (getEndtime() == null ? 0 : this.getEndtime().hashCode());
		return result;
	}

	public String getUsercode() {
		return usercode;
	}

	public void setUsercode(String usercode) {
		this.usercode = usercode;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
}